[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/giris"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/kayit"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/panel/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/randevular/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/danisanlar/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/ayarlar/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/yardim/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/blog/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/push/*"
  to = "/.netlify/functions/push-api/:splat"
  status = 200

[[redirects]]
  from = "/api/csp-report"
  to = "/.netlify/functions/csp-report"
  status = 200

[[redirects]]
  from = "/404"
  to = "/404.html"
  status = 404

[[redirects]]
  from = "/login"
  to = "/giris"
  status = 301

[[redirects]]
  from = "/register"
  to = "/kayit"
  status = 301

[[redirects]]
  from = "/dashboard/*"
  to = "/panel/:splat"
  status = 301

[[redirects]]
  from = "/appointments/*"
  to = "/randevular/:splat"
  status = 301

[[redirects]]
  from = "/clients/*"
  to = "/danisanlar/:splat"
  status = 301

[[redirects]]
  from = "/professionals/*"
  to = "/uzmanlar/:splat"
  status = 301

[[redirects]]
  from = "/settings/*"
  to = "/ayarlar/:splat"
  status = 301

[[redirects]]
  from = "/help/*"
  to = "/yardim/:splat"
  status = 301

[[redirects]]
  from = "/features"
  to = "/ozellikler"
  status = 301

[[redirects]]
  from = "/pricing"
  to = "/fiyatlandirma"
  status = 301

[[redirects]]
  from = "/privacy"
  to = "/gizlilik"
  status = 301

[[redirects]]
  from = "/terms"
  to = "/kosullar"
  status = 301

[[redirects]]
  from = "/contact"
  to = "/iletisim"
  status = 301

[[headers]]
  for = "/*"
    [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(self), interest-cohort=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com https://connect.facebook.net https://cdnjs.cloudflare.com https://psikoran.xyz https://*.jitsi.net https://meet.jit.si https://*.psikoran.xyz; connect-src 'self' https://*.supabase.co wss://*.supabase.co https://api.emailjs.com https://meet.jit.si wss://meet.jit.si https://psikoran.xyz https://*.psikoran.xyz wss://psikoran.xyz wss://*.psikoran.xyz https://*.google-analytics.com https://*.analytics.google.com https://*.googletagmanager.com https://*.jitsi.net wss://*.jitsi.net; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://*.jitsi.net https://meet.jit.si https://*.psikoran.xyz; font-src 'self' data: https://fonts.gstatic.com https://*.jitsi.net https://*.psikoran.xyz; img-src 'self' data: https://*.supabase.co https://*.amazonaws.com https://meet.jit.si https://psikoran.xyz https://*.psikoran.xyz https://*.google-analytics.com https://*.googletagmanager.com https://www.google.com https://www.google.tr https://*.jitsi.net; frame-src 'self' https://meet.jit.si https://psikoran.xyz https://*.psikoran.xyz https://*.googletagmanager.com https://*.jitsi.net; object-src 'none'; base-uri 'self'; form-action 'self'; upgrade-insecure-requests; block-all-mixed-content"
    Report-To = """
      {
        "group": "csp-endpoint",
        "max_age": 10886400,
        "endpoints": [
          { "url": "/api/csp-report" }
        ],
        "include_subdomains": true
      }
    """

[build.processing.html]
  pretty_urls = true

[[headers]]
  for = "/*.css"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.webp"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.png"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.jpg"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/manifest.json"
    [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/service-worker.js"
    [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 