[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/login"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/register"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/dashboard/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/appointments/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/clients/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/settings/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/help/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/blog/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/push/*"
  to = "/.netlify/functions/push-api/:splat"
  status = 200

[[redirects]]
  from = "/api/csp-report"
  to = "/.netlify/functions/csp-report"
  status = 200

[[redirects]]
  from = "/404"
  to = "/404.html"
  status = 404

[[headers]]
  for = "/*"
    [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(self), interest-cohort=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' https://www.googletagmanager.com https://connect.facebook.net https://cdnjs.cloudflare.com 'unsafe-inline';
      style-src 'self' https://fonts.googleapis.com 'unsafe-inline';
      img-src 'self' data: https://*.googleusercontent.com https://www.facebook.com https://psikoran.com https://*.supabase.co;
      font-src 'self' https://fonts.gstatic.com;
      connect-src 'self' https://www.google-analytics.com https://firebaseinstallations.googleapis.com https://fcmregistrations.googleapis.com https://firestore.googleapis.com https://identitytoolkit.googleapis.com https://securetoken.googleapis.com https://*.supabase.co wss://*.supabase.co;
      frame-src 'self' https://www.youtube.com https://meet.jit.si https://*.jitsi.net https://*.jitsi.org;
      media-src 'self' https://meet.jit.si;
      object-src 'none';
      base-uri 'self';
      form-action 'self';
      frame-ancestors 'none';
      report-uri https://psikoran.report-uri.com/r/d/csp/reportOnly;
    """
    Report-To = """
      {
        "group": "csp-endpoint",
        "max_age": 10886400,
        "endpoints": [
          { "url": "/api/csp-report" }
        ],
        "include_subdomains": true
      }
    """

[build.processing.html]
  pretty_urls = true

[[headers]]
  for = "/*.css"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.webp"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.png"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.jpg"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/manifest.json"
    [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/service-worker.js"
    [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 