export { Login } from './Login';
export { Register, CreateAssistant } from './CreateAssistant';
export { Dashboard } from './Dashboard';
export { Professionals } from './Professionals';
export { Clients } from './Clients';
export { ClientDetails } from './ClientDetails';
export { Appointments } from './Appointments';
export { Payments } from './Payments';
export { default as Settings } from './Settings';
export { ForgotPassword } from './ForgotPassword';
export { ResetPassword } from './ResetPassword';
export { Privacy } from './Privacy';
export { Terms } from './Terms';
export { KVKK } from './KVKK';
export { Contact } from './Contact';
export { Help } from './Help';
export { Test } from './Test';
export { TestCompleted } from './TestCompleted';
export { Home } from './Home';
export { Blog } from './Blog';
export { BlogPost } from './BlogPost';
export { BlogAdmin } from './BlogAdmin';